### ISSUE TITLE
`pipe` instead of `pipe21` in examples

### ISSUE THREAD

**Issue by ricardo-reis-1970** [tandav/pipe21#1]
Privet!

I found `pipe21` while checking on [`pipe`](https://github.com/JulienPalard/Pipe) on pypi and trying to find out something more usable. This `pipe21` is way better and I think it only lacks a bit of documentation (which I'd be happy to start putting together!)

However, after having installed both I noticed that the examples here all mention `pipe` instead of `pipe21` in the imports. Without `pipe` installed, this just gives a `ModuleNotFoundError`. With `pipe` installed, this goes to it, instead.

If one could vote for deprecation of stale libs and name release, I would totally do it. This is small, smart and I'll definitely be using it, as I am a fierce advocate for Functional Programming. But the examples must all be updated too (as you did in [rename pipe -> pipe21](https://github.com/tandav/pipe21/commit/016c9122ade9764cda3901af45d345bb32972109)), otherwise they won't work and adoption could be compromised.

Let me know what I can do to help.
Ricardo

**Comment by tandav** [comment]
I've created [file](https://github.com/tandav/pipe21/blob/master/reference.md) with a reference for all available methods, I'll try to fill it soon. Feel free to edit it if you want!
