### ISSUE TITLE
положняк положняк положняк положняк 

### ISSUE THREAD

**Issue by andrei-valikov** [tandav/pipe21#23]
я попугай и поэтому
положняк положняк положняк положняк положняк положняк положняк положняк положняк положняк положняк положняк положняк положняк 
чел норм
локально интересно
своих мыслей нет
только заимстованный мусор

**Comment by tandav** [comment]
окей доебался до выбора слов а не до сути, хотя суть была. Мб слишком много старых заезженных фраз но сказал как могу, пока так

**Comment by andrei-valikov** [comment]
«Итак, Шива — он и правда разрушитель!
Но он разрушитель невежества и болезней, всего отжившего и мешающего жизни.»

можешь быть против меня
но я буду искать твою свободу также как я нашёл свою
я знаю что ты тоже чувствуешь лицемерие
невозможно не чувствовать
и в тебе есть эта энергия протеста
пока ты не решаешься быть против лицемерия
пока ты выбираешь хобби, изоляцию, тихо мирно делать своё дело
как тебе кажется твоё
это только вопрос времени когда ты вспомнишь себя

**Comment by tandav** [comment]
Ты так и не сказал что ты делаешь. Выглядит как будто все сводится к доебкам до окружающих.  
То нельзя, это плохо, это иллюзии, тут маски итд.  
При этом в своей жизни нет ничего материального, все абстрактное, словесное за исключением еды и сна. Разрушать иллюзии понял, но что дальше, ничего? Что значит вспомнить себя? Просто сидеть и смотреть, только есть и спать и гулять?
Если так, то мне такое не подходит. Для меня это неприятно, потому что заглушает творческую энергию, желание изучать, пусть и неосознано и в иллюзии. Я не считаю это плохим, это часть жизни иногда ты в локальной иллюзии иногда наоборот на мета-загонах
